### ISSUE TITLE
[Security] Workflow main.yaml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by qazaqstan2025** [avi12/avi12#2]
The workflow main.yaml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by avi12** [comment]
Thank you for your report!
Should I simply change `v1` to `v2`?
https://github.com/avi12/avi12/blob/0859302ee357e4af4c6286977f1baa546842ec32/.github/workflows/main.yaml#L16

**Comment by avi12** [comment]
Did it
https://github.com/avi12/avi12/blob/682be03c120bee10df2e8dc582cfe0588335201b/.github/workflows/main.yaml#L16
